import streamlit as st
import joblib
import pandas as pd
from PIL import Image

# Create three columns: Left Logo, Middle Title, Right Logo
# The [1, 3, 1] ratio makes the title area wider than the logo areas
col1, col2, col3 = st.columns([1, 3, 1])

with col1:
    # Use 'use_container_width=True' to make it responsive
    st.image("logo.png", width=150) 

with col2:
    # Center the title text horizontally
    #st.markdown("<h1 style='text-align: center;'>🌱Crop Recommendation System</h1>", unsafe_allow_html=True)
    st.markdown("<h1 style='text-align: center;'>Crop Recommendation System</h1>", unsafe_allow_html=True)

with col3:
    st.image("Active_logo.png", width=150)
st.markdown("---") # Adds a divider line below the header

# 1. Load your saved model
model = joblib.load('crop_recommendation_model.pkl')

# 2. Pakistan Sowing Guide Dictionary
sowing_guide = {
    "rice": "Kharif Season: May to July",
    "maize": "Kharif: July-August | Spring: Feb-March",
    "chickpea": "Rabi Season: October to November",
    "kidneybeans": "Kharif: June-July",
    "pigeonpeas": "Kharif: April-May",
    "mothbeans": "Kharif: June-July",
    "mungbean": "Kharif: June-July | Spring: March-April",
    "blackgram": "Kharif: June-July",
    "lentil": "Rabi Season: October to November",
    "pomegranate": "Planting: Spring (Feb-March) or Monsoon (July-Aug)",
    "banana": "Planting: Spring or Autumn",
    "mango": "Planting: Feb-March or July-August",
    "grapes": "Planting: January to February",
    "watermelon": "Summer: February to March",
    "muskmelon": "Summer: February to March",
    "apple": "Winter Planting: December to February",
    "orange": "Spring: Feb-March | Autumn: Sep-Oct",
    "papaya": "Spring: Feb-March | Autumn: Sep-Oct",
    "coconut": "Monsoon: June to September",
    "cotton": "Kharif Season: April to May",
    "jute": "Kharif Season: March to May",
    "coffee": "Planting: Monsoon season",
    "wheat": "Rabi Season: November to December (Peak: Nov 15th)",
    "sugarcane": "Spring: Feb-March | Autumn: September",
    "mustard": "Rabi Season: October to November",
    "tobacco": "Spring: December to January (Nursery)"
}

# 3. App Header
st.set_page_config(page_title="Crop Recommender", page_icon="🌱")
#st.title("🌱 Precision Agriculture: Crop Recommender")
st.markdown("Enter soil and weather details to find the best crop for your land in Pakistan.")

# 4. Input fields
col1, col2 = st.columns(2)

with col1:
    st.subheader("Soil Nutrients")
    n = st.number_input("Nitrogen (N)", min_value=0, max_value=140, value=50)
    p = st.number_input("Phosphorus (P)", min_value=5, max_value=145, value=50)
    k = st.number_input("Potassium (K)", min_value=5, max_value=205, value=50)
    ph = st.number_input("Soil pH Level", min_value=3.5, max_value=9.9, value=6.5)

with col2:
    st.subheader("Climate Conditions")
    temp = st.number_input("Temperature (°C)", value=25.0)
    hum = st.number_input("Humidity (%)", min_value=0.0, max_value=100.0, value=60.0)
    rain = st.number_input("Rainfall (mm)", value=100.0)

st.divider()

# 5. Prediction Logic
if st.button("Recommend Crop", type="primary", key="main_predict_btn"):
    # Format inputs for the model
    input_data = [[n, p, k, temp, hum, ph, rain]]
    prediction = model.predict(input_data)
    crop_name = prediction[0].lower()
    
    # Display the Result
    st.header(f"Recommended Crop: {crop_name.upper()}")
    st.success(f"Based on your data, **{crop_name.upper()}** is the best choice for your land.")

    # 6. Pakistan Sowing Advice
    if crop_name in sowing_guide:
        st.info(f"📅 **Best Sowing Time (Pakistan):** {sowing_guide[crop_name]}")

    # 7. Generate Downloadable Report
    report_text = f"""
    --- CROP RECOMMENDATION REPORT ---
    Generated for: Rawalpindi/Islamabad Region
    
    INPUT DATA:
    - Nitrogen: {n} | Phosphorus: {p} | Potassium: {k}
    - pH Level: {ph}
    - Temperature: {temp}°C | Humidity: {hum}% | Rainfall: {rain}mm
    
    RESULT:
    - Recommended Crop: {crop_name.upper()}
    - Sowing Schedule: {sowing_guide.get(crop_name, 'Contact local agri-office')}
    
    ----------------------------------
    Generated by Precision Agriculture System.
    """

    st.download_button(
        label="📥 Download Recommendation Report",
        data=report_text,
        file_name=f"crop_report_{crop_name}.txt",
        mime="text/plain",
        key="download_report_btn"
    )
st.sidebar.title("System Info")
st.sidebar.info("""
**Note:** This model is currently trained on 22 crops including Rice, Maize, and Cotton. 
Wheat and Sugarcane recommendations are coming in version 2.0!

""")











